module Video.MediaInfo.TestData
  ( t0, t1, t2, t3, t4, t5, t6 )
where

import Base1
import Data.ByteString.Lazy
import Data.Text.Encoding  ( encodeUtf8 )

t0 ∷ Data.ByteString.Lazy.ByteString
t0 = ""

t1 ∷ Data.ByteString.Lazy.ByteString
t1 = "{ \"media\": { \"@ref\" : \"/file\", \"track\": [] } }"

creatingLibrary ∷ Data.ByteString.Lazy.ByteString
creatingLibrary = ю [ "  \"creatingLibrary\": {"
                    , "    \"name\": \"MediaInfoLib\","
                    , "    \"version\": \"25.04\","
                    , "    \"url\": \"https://mediaarea.net/MediaInfo\""
                    , "  },"
                    ]


t2 ∷ Data.ByteString.Lazy.ByteString
t2 = ю [ "{"
       , creatingLibrary
       , "  \"media\": {"
       , "    \"@ref\": \"/local/martyn/TV/Alien: Earth - 01x03.mkv\","
       , "    \"track\": ["
       , "    ]"
       , "  }"
       , "}"
       ]

typeGeneral ∷ Data.ByteString.Lazy.ByteString
typeGeneral =
  ю [ "     {"
    , "       \"@type\": \"General\","
    , "       \"UniqueID\": \"297636061216975995556366757693915800471\","
    , "       \"VideoCount\": \"1\","
    , "       \"AudioCount\": \"1\","
    , "       \"TextCount\": \"23\","
    , "       \"FileExtension\": \"mkv\","
    , "       \"Format\": \"Matroska\","
    , "       \"Format_Version\": \"4\","
    , "       \"FileSize\": \"2116638261\","
    , "       \"Duration\": \"3259.552\","
    , "       \"OverallBitRate_Mode\": \"VBR\","
    , "       \"OverallBitRate\": \"5194918\","
    , "       \"FrameRate\": \"24.000\","
    , "       \"FrameCount\": \"78228\","
    , "       \"StreamSize\": \"1196948\","
    , "       \"IsStreamable\": \"Yes\","
    , "       \"File_Modified_Date\": \"2025-08-21 10:12:59 UTC\","
    , "       \"File_Modified_Date_Local\": \"2025-08-21 10:12:59\","
    , "       \"Encoded_Application\": \"mkvmerge v90.0 ('Hanging On') 64-bit\","
    , "       \"Encoded_Library\": \"libebml v1.4.4 + libmatroska v1.7.1\""
    , "     }" -- note no comma here
    ]

t3 ∷ Data.ByteString.Lazy.ByteString
t3 = ю [ "{"
       , creatingLibrary
       , "  \"media\": {"
       , "    \"@ref\": \"/local/martyn/TV/Alien: Earth - 01x03.mkv\","
       , "    \"track\": ["
       ,        typeGeneral
       , "    ]"
       , "  }"
       , "}"
       ]
typeVideo ∷ Data.ByteString.Lazy.ByteString
typeVideo =
  ю [ "      {"
    , "        \"@type\": \"Video\","
    , "        \"StreamOrder\": \"0\","
    , "        \"ID\": \"1\","
    , "        \"UniqueID\": \"6573738665338430009\","
    , "        \"Format\": \"AVC\","
    , "        \"Format_Profile\": \"High\","
    , "        \"Format_Level\": \"4\","
    , "        \"Format_Settings_CABAC\": \"Yes\","
    , "        \"Format_Settings_RefFrames\": \"4\","
    , "        \"CodecID\": \"V_MPEG4/ISO/AVC\","
    , "        \"Duration\": \"3259.500000000\","
    , "        \"BitRate_Mode\": \"VBR\","
    , "        \"BitRate\": \"4935336\","
    , "        \"BitRate_Maximum\": \"12749952\","
    , "        \"Width\": \"1920\","
    , "        \"Height\": \"1080\","
    , "        \"Stored_Height\": \"1088\","
    , "        \"Sampled_Width\": \"1920\","
    , "        \"Sampled_Height\": \"1080\","
    , "        \"PixelAspectRatio\": \"1.000\","
    , "        \"DisplayAspectRatio\": \"1.778\","
    , "        \"FrameRate_Mode\": \"CFR\","
    , "        \"FrameRate\": \"24.000\","
    , "        \"FrameRate_Num\": \"24\","
    , "        \"FrameRate_Den\": \"1\","
    , "        \"FrameCount\": \"78228\","
    , "        \"ColorSpace\": \"YUV\","
    , "        \"ChromaSubsampling\": \"4:2:0\","
    , "        \"BitDepth\": \"8\","
    , "        \"ScanType\": \"Progressive\","
    , "        \"Delay\": \"0.000\","
    , "        \"Delay_Source\": \"Container\","
    , "        \"TimeCode_FirstFrame\": \"00:00:00;00\","
    , "        \"StreamSize\": \"2010841200\","
    , "        \"Default\": \"Yes\","
    , "        \"Forced\": \"No\","
    , "        \"BufferSize\": \"17000000\","
    , "        \"colour_description_present\": \"Yes\","
    , "        \"colour_description_present_Source\": \"Stream\","
    , "        \"colour_range\": \"Limited\","
    , "        \"colour_range_Source\": \"Stream\","
    , "        \"colour_primaries\": \"BT.709\","
    , "        \"colour_primaries_Source\": \"Stream\","
    , "        \"transfer_characteristics\": \"BT.709\","
    , "        \"transfer_characteristics_Source\": \"Stream\","
    , "        \"matrix_coefficients\": \"BT.709\","
    , "        \"matrix_coefficients_Source\": \"Stream\""
    , "      }"
    ]

t4 ∷ Data.ByteString.Lazy.ByteString
t4 = ю [ "{"
       , creatingLibrary
       , "  \"media\": {"
       , "    \"@ref\": \"/local/martyn/TV/Alien: Earth - 01x03.mkv\","
       , "    \"track\": ["
       ,        typeGeneral -- note comma lacking
       ,        ","
       ,        typeVideo
       , "    ]"
       , "  }"
       , "}"
       ]

typeAudio ∷ Data.ByteString.Lazy.ByteString
typeAudio =
  ю [ "      {"
    , "        \"@type\": \"Audio\","
    , "        \"StreamOrder\": \"1\","
    , "        \"ID\": \"2\","
    , "        \"UniqueID\": \"10645032463989026813\","
    , "        \"Format\": \"E-AC-3\","
    , "        \"Format_Commercial_IfAny\": \"Dolby Digital Plus\","
    , "        \"Format_Settings_Endianness\": \"Big\","
    , "        \"CodecID\": \"A_EAC3\","
    , "        \"Duration\": \"3259.552000000\","
    , "        \"BitRate_Mode\": \"CBR\","
    , "        \"BitRate\": \"256000\","
    , "        \"Channels\": \"6\","
    , "        \"ChannelPositions\": \"Front: L C R, Side: L R, LFE\","
    , "        \"ChannelLayout\": \"L R C LFE Ls Rs\","
    , "        \"SamplesPerFrame\": \"1536\","
    , "        \"SamplingRate\": \"48000\","
    , "        \"SamplingCount\": \"156458496\","
    , "        \"FrameRate\": \"31.250\","
    , "        \"FrameCount\": \"101861\","
    , "        \"Compression_Mode\": \"Lossy\","
    , "        \"Delay\": \"0.000\","
    , "        \"Delay_Source\": \"Container\","
    , "        \"Video_Delay\": \"0.000\","
    , "        \"StreamSize\": \"104305664\","
    , "        \"Language\": \"en\","
    , "        \"ServiceKind\": \"CM\","
    , "        \"Default\": \"Yes\","
    , "        \"Forced\": \"No\","
    , "        \"extra\": {"
    , "          \"bsid\": \"16\","
    , "          \"dialnorm\": \"-27\","
    , "          \"compr\": \"-0.28\","
    , "          \"acmod\": \"7\","
    , "          \"lfeon\": \"1\","
    , "          \"mixlevel\": \"105\","
    , "          \"roomtyp\": \"Small\","
    , "          \"dialnorm_Average\": \"-27\","
    , "          \"dialnorm_Minimum\": \"-27\","
    , "          \"compr_Average\": \"-1.03\","
    , "          \"compr_Minimum\": \"-6.02\","
    , "          \"compr_Maximum\": \"5.46\","
    , "          \"compr_Count\": \"1322\""
    , "        }"
    , "      }"
    ]

t5 ∷ Data.ByteString.Lazy.ByteString
t5 = ю [ "{"
       , creatingLibrary
       , "  \"media\": {"
       , "    \"@ref\": \"/local/martyn/TV/Alien: Earth - 01x03.mkv\","
       , "    \"track\": ["
       ,        typeGeneral -- note comma lacking
       ,        ","
       ,        typeVideo
       ,        ","
       ,        typeAudio
       , "    ]"
       , "  }"
       , "}"
       ]

sub1 ∷ Data.ByteString.Lazy.ByteString
sub1 =
  ю [ "      {"
    , "        \"@type\": \"Text\","
    , "        \"@typeorder\": \"1\","
    , "        \"StreamOrder\": \"2\","
    , "        \"ID\": \"3\","
    , "        \"UniqueID\": \"11382417218140862655\","
    , "        \"Format\": \"UTF-8\","
    , "        \"CodecID\": \"S_TEXT/UTF8\","
    , "        \"Duration\": \"3158.042000000\","
    , "        \"BitRate\": \"42\","
    , "        \"FrameRate\": \"0.202\","
    , "        \"FrameCount\": \"637\","
    , "        \"ElementCount\": \"637\","
    , "        \"StreamSize\": \"16972\","
    , "        \"Title\": \"English (SDH)\","
    , "        \"Language\": \"en\","
    , "        \"Default\": \"Yes\","
    , "        \"Forced\": \"No\""
    , "      }"
    ]

sub2 ∷ Data.ByteString.Lazy.ByteString
sub2 =
  ю $ fromStrict ∘ encodeUtf8 ⊳
    [ "      {"
    , "        \"@type\": \"Text\","
    , "        \"@typeorder\": \"2\","
    , "        \"StreamOrder\": \"3\","
    , "        \"ID\": \"4\","
    , "        \"UniqueID\": \"16366645791972011626\","
    , "        \"Format\": \"UTF-8\","
    , "        \"CodecID\": \"S_TEXT/UTF8\","
    , "        \"Duration\": \"3195.125000000\","
    , "        \"BitRate\": \"28\","
    , "        \"FrameRate\": \"0.141\","
    , "        \"FrameCount\": \"449\","
    , "        \"ElementCount\": \"449\","
    , "        \"StreamSize\": \"11308\","
    , "        \"Title\": \"Čeština\","
    , "        \"Language\": \"cs\","
    , "        \"Default\": \"No\","
    , "        \"Forced\": \"No\""
    , "      }"
    ]

t6 ∷ Data.ByteString.Lazy.ByteString
t6 = ю [ "{"
       , creatingLibrary
       , "  \"media\": {"
       , "    \"@ref\": \"/local/martyn/TV/Alien: Earth - 01x03.mkv\","
       , "    \"track\": ["
       ,        typeGeneral -- note comma lacking
       ,        ","
       ,        typeVideo
       ,        ","
       ,        typeAudio
       ,        ","
       ,        sub1
       ,        ","
       ,        sub2
--       , "      {"
--       , "        \"@type\": \"Text\","
--       , "        \"@typeorder\": \"3\","
--       , "        \"StreamOrder\": \"4\","
--       , "        \"ID\": \"5\","
--       , "        \"UniqueID\": \"18073125349724727529\","
--       , "        \"Format\": \"UTF-8\","
--       , "        \"CodecID\": \"S_TEXT/UTF8\","
--       , "        \"Duration\": \"3160.250000000\","
--       , "        \"BitRate\": \"30\","
--       , "        \"FrameRate\": \"0.147\","
--       , "        \"FrameCount\": \"465\","
--       , "        \"ElementCount\": \"465\","
--       , "        \"StreamSize\": \"11897\","
--       , "        \"Title\": \"Dansk\","
--       , "        \"Language\": \"da\","
--       , "        \"Default\": \"No\","
--       , "        \"Forced\": \"No\""
--       , "      },"
--       , "      {"
--       , "        \"@type\": \"Text\","
--       , "        \"@typeorder\": \"4\","
--       , "        \"StreamOrder\": \"5\","
--       , "        \"ID\": \"6\","
--       , "        \"UniqueID\": \"10643657023651477610\","
--       , "        \"Format\": \"UTF-8\","
--       , "        \"CodecID\": \"S_TEXT/UTF8\","
--       , "        \"Duration\": \"3160.250000000\","
--       , "        \"BitRate\": \"33\","
--       , "        \"FrameRate\": \"0.152\","
--       , "        \"FrameCount\": \"480\","
--       , "        \"ElementCount\": \"480\","
--       , "        \"StreamSize\": \"13140\","
--       , "        \"Title\": \"Deutsch\","
--       , "        \"Language\": \"de\","
--       , "        \"Default\": \"No\","
--       , "        \"Forced\": \"No\""
--       , "      },"
--       , "      {"
--       , "        \"@type\": \"Text\","
--       , "        \"@typeorder\": \"5\","
--       , "        \"StreamOrder\": \"6\","
--       , "        \"ID\": \"7\","
--       , "        \"UniqueID\": \"16717916893820167364\","
--       , "        \"Format\": \"UTF-8\","
--       , "        \"CodecID\": \"S_TEXT/UTF8\","
--       , "        \"Duration\": \"3160.250000000\","
--       , "        \"BitRate\": \"53\","
--       , "        \"FrameRate\": \"0.143\","
--       , "        \"FrameCount\": \"452\","
--       , "        \"ElementCount\": \"452\","
--       , "        \"StreamSize\": \"20956\","
--       , "        \"Title\": \"Greek\","
--       , "        \"Language\": \"el\","
--       , "        \"Default\": \"No\","
--       , "        \"Forced\": \"No\""
--       , "      },"
--       , "      {"
--       , "        \"@type\": \"Text\","
--       , "        \"@typeorder\": \"6\","
--       , "        \"StreamOrder\": \"7\","
--       , "        \"ID\": \"8\","
--       , "        \"UniqueID\": \"5226970332238630977\","
--       , "        \"Format\": \"UTF-8\","
--       , "        \"CodecID\": \"S_TEXT/UTF8\","
--       , "        \"Duration\": \"3160.250000000\","
--       , "        \"BitRate\": \"30\","
--       , "        \"FrameRate\": \"0.146\","
--       , "        \"FrameCount\": \"462\","
--       , "        \"ElementCount\": \"462\","
--       , "        \"StreamSize\": \"12175\","
--       , "        \"Title\": \"Español (Latinoamericano)\","
--       , "        \"Language\": \"es\","
--       , "        \"Default\": \"No\","
--       , "        \"Forced\": \"No\""
--       , "      },"
--       , "      {"
--       , "        \"@type\": \"Text\","
--       , "        \"@typeorder\": \"7\","
--       , "        \"StreamOrder\": \"8\","
--       , "        \"ID\": \"9\","
--       , "        \"UniqueID\": \"16524072082367660210\","
--       , "        \"Format\": \"UTF-8\","
--       , "        \"CodecID\": \"S_TEXT/UTF8\","
--       , "        \"Duration\": \"3195.125000000\","
--       , "        \"BitRate\": \"30\","
--       , "        \"FrameRate\": \"0.150\","
--       , "        \"FrameCount\": \"478\","
--       , "        \"ElementCount\": \"478\","
--       , "        \"StreamSize\": \"12277\","
--       , "        \"Title\": \"Español\","
--       , "        \"Language\": \"es\","
--       , "        \"Default\": \"No\","
--       , "        \"Forced\": \"No\""
--       , "      },"
--       , "      {"
--       , "        \"@type\": \"Text\","
--       , "        \"@typeorder\": \"8\","
--       , "        \"StreamOrder\": \"9\","
--       , "        \"ID\": \"10\","
--       , "        \"UniqueID\": \"2996389384329645252\","
--       , "        \"Format\": \"UTF-8\","
--       , "        \"CodecID\": \"S_TEXT/UTF8\","
--       , "        \"Duration\": \"3160.250000000\","
--       , "        \"BitRate\": \"29\","
--       , "        \"FrameRate\": \"0.147\","
--       , "        \"FrameCount\": \"466\","
--       , "        \"ElementCount\": \"466\","
--       , "        \"StreamSize\": \"11762\","
--       , "        \"Title\": \"Suomi\","
--       , "        \"Language\": \"fi\","
--       , "        \"Default\": \"No\","
--       , "        \"Forced\": \"No\""
--       , "      },"
--       , "      {"
--       , "        \"@type\": \"Text\","
--       , "        \"@typeorder\": \"9\","
--       , "        \"StreamOrder\": \"10\","
--       , "        \"ID\": \"11\","
--       , "        \"UniqueID\": \"15536313324727926585\","
--       , "        \"Format\": \"UTF-8\","
--       , "        \"CodecID\": \"S_TEXT/UTF8\","
--       , "        \"Duration\": \"3160.250000000\","
--       , "        \"BitRate\": \"31\","
--       , "        \"FrameRate\": \"0.145\","
--       , "        \"FrameCount\": \"459\","
--       , "        \"ElementCount\": \"459\","
--       , "        \"StreamSize\": \"12275\","
--       , "        \"Title\": \"Français\","
--       , "        \"Language\": \"fr\","
--       , "        \"Default\": \"No\","
--       , "        \"Forced\": \"No\""
--       , "      },"
--       , "      {"
--       , "        \"@type\": \"Text\","
--       , "        \"@typeorder\": \"10\","
--       , "        \"StreamOrder\": \"11\","
--       , "        \"ID\": \"12\","
--       , "        \"UniqueID\": \"16292709872444363062\","
--       , "        \"Format\": \"UTF-8\","
--       , "        \"CodecID\": \"S_TEXT/UTF8\","
--       , "        \"Duration\": \"3195.125000000\","
--       , "        \"BitRate\": \"31\","
--       , "        \"FrameRate\": \"0.138\","
--       , "        \"FrameCount\": \"440\","
--       , "        \"ElementCount\": \"440\","
--       , "        \"StreamSize\": \"12554\","
--       , "        \"Title\": \"Magyar\","
--       , "        \"Language\": \"hu\","
--       , "        \"Default\": \"No\","
--       , "        \"Forced\": \"No\""
--       , "      },"
--       , "      {"
--       , "        \"@type\": \"Text\","
--       , "        \"@typeorder\": \"11\","
--       , "        \"StreamOrder\": \"12\","
--       , "        \"ID\": \"13\","
--       , "        \"UniqueID\": \"10525262238359863125\","
--       , "        \"Format\": \"UTF-8\","
--       , "        \"CodecID\": \"S_TEXT/UTF8\","
--       , "        \"Duration\": \"2725.250000000\","
--       , "        \"BitRate\": \"34\","
--       , "        \"FrameRate\": \"0.171\","
--       , "        \"FrameCount\": \"467\","
--       , "        \"ElementCount\": \"467\","
--       , "        \"StreamSize\": \"11907\","
--       , "        \"Title\": \"Italiano\","
--       , "        \"Language\": \"it\","
--       , "        \"Default\": \"No\","
--       , "        \"Forced\": \"No\""
--       , "      },"
--       , "      {"
--       , "        \"@type\": \"Text\","
--       , "        \"@typeorder\": \"12\","
--       , "        \"StreamOrder\": \"13\","
--       , "        \"ID\": \"14\","
--       , "        \"UniqueID\": \"14835093456785206962\","
--       , "        \"Format\": \"UTF-8\","
--       , "        \"CodecID\": \"S_TEXT/UTF8\","
--       , "        \"Duration\": \"3195.125000000\","
--       , "        \"BitRate\": \"27\","
--       , "        \"FrameRate\": \"0.149\","
--       , "        \"FrameCount\": \"475\","
--       , "        \"ElementCount\": \"475\","
--       , "        \"StreamSize\": \"11116\","
--       , "        \"Title\": \"Japanese\","
--       , "        \"Language\": \"ja\","
--       , "        \"Default\": \"No\","
--       , "        \"Forced\": \"No\""
--       , "      },"
--       , "      {"
--       , "        \"@type\": \"Text\","
--       , "        \"@typeorder\": \"13\","
--       , "        \"StreamOrder\": \"14\","
--       , "        \"ID\": \"15\","
--       , "        \"UniqueID\": \"6928208620759373788\","
--       , "        \"Format\": \"UTF-8\","
--       , "        \"CodecID\": \"S_TEXT/UTF8\","
--       , "        \"Duration\": \"3195.125000000\","
--       , "        \"BitRate\": \"37\","
--       , "        \"FrameRate\": \"0.151\","
--       , "        \"FrameCount\": \"482\","
--       , "        \"ElementCount\": \"482\","
--       , "        \"StreamSize\": \"14863\","
--       , "        \"Title\": \"Korean\","
--       , "        \"Language\": \"ko\","
--       , "        \"Default\": \"No\","
--       , "        \"Forced\": \"No\""
--       , "      },"
--       , "      {"
--       , "        \"@type\": \"Text\","
--       , "        \"@typeorder\": \"14\","
--       , "        \"StreamOrder\": \"15\","
--       , "        \"ID\": \"16\","
--       , "        \"UniqueID\": \"7485374204617178076\","
--       , "        \"Format\": \"UTF-8\","
--       , "        \"CodecID\": \"S_TEXT/UTF8\","
--       , "        \"Duration\": \"3160.250000000\","
--       , "        \"BitRate\": \"28\","
--       , "        \"FrameRate\": \"0.097\","
--       , "        \"FrameCount\": \"306\","
--       , "        \"ElementCount\": \"306\","
--       , "        \"StreamSize\": \"11248\","
--       , "        \"Title\": \"Nederlands\","
--       , "        \"Language\": \"nl\","
--       , "        \"Default\": \"No\","
--       , "        \"Forced\": \"No\""
--       , "      },"
--       , "      {"
--       , "        \"@type\": \"Text\","
--       , "        \"@typeorder\": \"15\","
--       , "        \"StreamOrder\": \"16\","
--       , "        \"ID\": \"17\","
--       , "        \"UniqueID\": \"7117129779742673952\","
--       , "        \"Format\": \"UTF-8\","
--       , "        \"CodecID\": \"S_TEXT/UTF8\","
--       , "        \"Duration\": \"3160.250000000\","
--       , "        \"BitRate\": \"30\","
--       , "        \"FrameRate\": \"0.150\","
--       , "        \"FrameCount\": \"473\","
--       , "        \"ElementCount\": \"473\","
--       , "        \"StreamSize\": \"12035\","
--       , "        \"Title\": \"Norsk\","
--       , "        \"Language\": \"no\","
--       , "        \"Default\": \"No\","
--       , "        \"Forced\": \"No\""
--       , "      },"
--       , "      {"
--       , "        \"@type\": \"Text\","
--       , "        \"@typeorder\": \"16\","
--       , "        \"StreamOrder\": \"17\","
--       , "        \"ID\": \"18\","
--       , "        \"UniqueID\": \"16280584886284661406\","
--       , "        \"Format\": \"UTF-8\","
--       , "        \"CodecID\": \"S_TEXT/UTF8\","
--       , "        \"Duration\": \"3195.125000000\","
--       , "        \"BitRate\": \"29\","
--       , "        \"FrameRate\": \"0.148\","
--       , "        \"FrameCount\": \"474\","
--       , "        \"ElementCount\": \"474\","
--       , "        \"StreamSize\": \"11882\","
--       , "        \"Title\": \"Polski\","
--       , "        \"Language\": \"pl\","
--       , "        \"Default\": \"No\","
--       , "        \"Forced\": \"No\""
--       , "      },"
--       , "      {"
--       , "        \"@type\": \"Text\","
--       , "        \"@typeorder\": \"17\","
--       , "        \"StreamOrder\": \"18\","
--       , "        \"ID\": \"19\","
--       , "        \"UniqueID\": \"14742765433648497569\","
--       , "        \"Format\": \"UTF-8\","
--       , "        \"CodecID\": \"S_TEXT/UTF8\","
--       , "        \"Duration\": \"3160.250000000\","
--       , "        \"BitRate\": \"31\","
--       , "        \"FrameRate\": \"0.140\","
--       , "        \"FrameCount\": \"442\","
--       , "        \"ElementCount\": \"442\","
--       , "        \"StreamSize\": \"12320\","
--       , "        \"Title\": \"Português (Brasil)\","
--       , "        \"Language\": \"pt\","
--       , "        \"Default\": \"No\","
--       , "        \"Forced\": \"No\""
--       , "      },"
--       , "      {"
--       , "        \"@type\": \"Text\","
--       , "        \"@typeorder\": \"18\","
--       , "        \"StreamOrder\": \"19\","
--       , "        \"ID\": \"20\","
--       , "        \"UniqueID\": \"8721397021063535341\","
--       , "        \"Format\": \"UTF-8\","
--       , "        \"CodecID\": \"S_TEXT/UTF8\","
--       , "        \"Duration\": \"3195.125000000\","
--       , "        \"BitRate\": \"30\","
--       , "        \"FrameRate\": \"0.145\","
--       , "        \"FrameCount\": \"464\","
--       , "        \"ElementCount\": \"464\","
--       , "        \"StreamSize\": \"12141\","
--       , "        \"Title\": \"Português\","
--       , "        \"Language\": \"pt\","
--       , "        \"Default\": \"No\","
--       , "        \"Forced\": \"No\""
--       , "      },"
--       , "      {"
--       , "        \"@type\": \"Text\","
--       , "        \"@typeorder\": \"19\","
--       , "        \"StreamOrder\": \"20\","
--       , "        \"ID\": \"21\","
--       , "        \"UniqueID\": \"13160838047852246590\","
--       , "        \"Format\": \"UTF-8\","
--       , "        \"CodecID\": \"S_TEXT/UTF8\","
--       , "        \"Duration\": \"3160.250000000\","
--       , "        \"BitRate\": \"31\","
--       , "        \"FrameRate\": \"0.126\","
--       , "        \"FrameCount\": \"399\","
--       , "        \"ElementCount\": \"399\","
--       , "        \"StreamSize\": \"12395\","
--       , "        \"Title\": \"Română\","
--       , "        \"Language\": \"ro\","
--       , "        \"Default\": \"No\","
--       , "        \"Forced\": \"No\""
--       , "      },"
--       , "      {"
--       , "        \"@type\": \"Text\","
--       , "        \"@typeorder\": \"20\","
--       , "        \"StreamOrder\": \"21\","
--       , "        \"ID\": \"22\","
--       , "        \"UniqueID\": \"1034800424657298313\","
--       , "        \"Format\": \"UTF-8\","
--       , "        \"CodecID\": \"S_TEXT/UTF8\","
--       , "        \"Duration\": \"3195.125000000\","
--       , "        \"BitRate\": \"31\","
--       , "        \"FrameRate\": \"0.151\","
--       , "        \"FrameCount\": \"482\","
--       , "        \"ElementCount\": \"482\","
--       , "        \"StreamSize\": \"12402\","
--       , "        \"Title\": \"Slovenčina\","
--       , "        \"Language\": \"sk\","
--       , "        \"Default\": \"No\","
--       , "        \"Forced\": \"No\""
--       , "      },"
--       , "      {"
--       , "        \"@type\": \"Text\","
--       , "        \"@typeorder\": \"21\","
--       , "        \"StreamOrder\": \"22\","
--       , "        \"ID\": \"23\","
--       , "        \"UniqueID\": \"13029076329844643023\","
--       , "        \"Format\": \"UTF-8\","
--       , "        \"CodecID\": \"S_TEXT/UTF8\","
--       , "        \"Duration\": \"3160.250000000\","
--       , "        \"BitRate\": \"30\","
--       , "        \"FrameRate\": \"0.130\","
--       , "        \"FrameCount\": \"412\","
--       , "        \"ElementCount\": \"412\","
--       , "        \"StreamSize\": \"12194\","
--       , "        \"Title\": \"Svenska\","
--       , "        \"Language\": \"sv\","
--       , "        \"Default\": \"No\","
--       , "        \"Forced\": \"No\""
--       , "      },"
--       , "      {"
--       , "        \"@type\": \"Text\","
--       , "        \"@typeorder\": \"22\","
--       , "        \"StreamOrder\": \"23\","
--       , "        \"ID\": \"24\","
--       , "        \"UniqueID\": \"5701834229437807533\","
--       , "        \"Format\": \"UTF-8\","
--       , "        \"CodecID\": \"S_TEXT/UTF8\","
--       , "        \"Duration\": \"3160.250000000\","
--       , "        \"BitRate\": \"32\","
--       , "        \"FrameRate\": \"0.152\","
--       , "        \"FrameCount\": \"479\","
--       , "        \"ElementCount\": \"479\","
--       , "        \"StreamSize\": \"12864\","
--       , "        \"Title\": \"Türkçe\","
--       , "        \"Language\": \"tr\","
--       , "        \"Default\": \"No\","
--       , "        \"Forced\": \"No\""
--       , "      },"
--       , "      {"
--       , "        \"@type\": \"Text\","
--       , "        \"@typeorder\": \"23\","
--       , "        \"StreamOrder\": \"24\","
--       , "        \"ID\": \"25\","
--       , "        \"UniqueID\": \"14502630713129737170\","
--       , "        \"Format\": \"UTF-8\","
--       , "        \"CodecID\": \"S_TEXT/UTF8\","
--       , "        \"Duration\": \"3195.125000000\","
--       , "        \"BitRate\": \"29\","
--       , "        \"FrameRate\": \"0.151\","
--       , "        \"FrameCount\": \"482\","
--       , "        \"ElementCount\": \"482\","
--       , "        \"StreamSize\": \"11766\","
--       , "        \"Title\": \"Chinese (Traditional)\","
--       , "        \"Language\": \"zh\","
--       , "        \"Default\": \"No\","
--       , "        \"Forced\": \"No\""
--       , "      }"
       , "    ]"
       , "  }"
       , "}"
       ]

-- that's all, folks! ----------------------------------------------------------
